spring:
  config:
    import: application-secret.properties
  web:
    resources:
      add-mappings: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  data:
    redis:
      host: ${DEV_REDIS_HOST}
      port: ${DEV_REDIS_PORT}

jwt:
  secretKey: ${JWT_SECRET_KEY}
  access:
    expiration: ${JWT_ACCESS_TOKEN_EXPIRE_TIME}
    header: ${JWT_ACCESS_TOKEN_HEADER}
  refresh:
    expiration: ${JWT_REFRESH_TOKEN_EXPIRE_TIME}
    header: ${JWT_REFRESH_TOKEN_HEADER}