spring:
  config:
    activate:
      on-profile: local
    import:
      - classpath:jpa.yml
      - classpath:external.yml
      - classpath:jwt.yml
  web:
    resources:
      add-mappings: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS}