spring.config.activate.on-profile: dev
spring:
  jpa:
    hibernate:
      ddl-auto: none
---
spring.config.activate.on-profile: local
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

---
spring.config.activate.on-profile: test
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop