name: GLOBAL SOOKMYUNG dev CI

on:
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: build
        run: |
          chmod +x gradlew
          ./gradlew build
        shell: bash