name: Glabal Sookmyung main CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create .env file
        run: | 
          cd ./src/main/resources
          echo "${{ secrets.TEST_ENV }}" > .env

      - name: Export environment variables from .env
        run: |
          set -a 
          source ./src/main/resources/.env 
          set +a

      - name: build
        run: |
          chmod +x gradlew
          ./gradlew build
        shell: bash